name: Run tests
on:
  push:
    branches:
    # Only mainline branches, features etc are covered on the pull_request trigger
    - '*.x'
  pull_request:

jobs:
  run-tests:
    runs-on: ubuntu-latest
    name: Run tests
    steps:
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: 8.2
        tools: composer:v2

    - name: Checkout
      uses: actions/checkout@v2

    - name: Get Composer Cache Directory
      id: composer-cache
      run: |
        echo "::set-output name=dir::$(composer config cache-files-dir)"

    - uses: actions/cache@v2
      with:
        path: ${{ steps.composer-cache.outputs.dir }}
        key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-composer

    - name: Install composer dependencies
      run: composer install --no-interaction --no-progress

    - name: Run unit tests
      run: |
        vendor/bin/phpunit --testsuite unit

    - name: Run integration tests
      run: |
        vendor/bin/phpunit --testsuite integration

    - name: Run blackbox tests
      run: test/run-blackbox-tests.sh
